LIST_ELEM = ['H', 'He', 'C', 'N', 'O', 'Ne', 'Ar', 'S', 'Cl', 'Fe', 'Si']

LIST_ALL_ELEM = ['H', 'He', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Ne', 'Na', 'Mg',
                 'Al', 'Si', 'P', 'S', 'Cl', 'Ar', 'K', 'Ca',
                 'Sc', 'Ti', 'V', 'Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn']

SYM2ELEM = {'H' : 'hydrogen',
            'He' : 'helium',
            'Li': 'lithium',
            'Be': 'beryllium',
            'B' : 'boron',
            'C' : 'carbon',
            'N' : 'nitrogen',
            'O' : 'oxygen',
            'F' : 'fluorine',
            'Ne' : 'neon',
            'Na' : 'sodium',
            'Mg' : 'magnesium',
            'Al' : 'aluminium',
            'Si' : 'silicon',
            'P' : 'phosphorus',
            'S' : 'sulphur',
            'Cl' : 'chlorine',
            'Ar' : 'argon',
            'K' : 'potassium',
            'Ca' : 'calcium',
            'Sc' : 'scandium',
            'Ti' : 'titanium',
            'V' : 'vanadium',
            'Cr' : 'chromium',
            'Mn' : 'manganese',
            'Fe' : 'iron',
            'Co' : 'cobalt',
            'Ni' : 'nickel',
            'Cu' : 'copper',
            'Zn' : 'zinc'}
